export type StepType = "narrate" | "choice" | "distribute" | "slice" | "distribute-halves" | "show-number" | "show-fraction"

export interface Choice {
  label: string;
  next: string;
  correct?: boolean;
}

export interface LessonStep {
  id: string;
  type: StepType;
  tutorText?: string;
  taskHeader?: string;
  choices?: Choice[];
  next?: string;
  cookieCount?: number;
  characterCount?: number;
  expectedPerPerson?: number;
  showNumber?: string;
  showFractionNum?: number;
  showFractionDen?: number;
  wholeNumber?: number;
  allowKnife?: boolean;
  sfx?: string;
}

export const lessonSteps: Record<string, LessonStep> = {
  // ── STAGE 1: Review Halves ──────────────────────────────────
  "start": {
    id: "start",
    type: "narrate",
    tutorText: "Welcome to the Toy Workshop! This is where little robot elves build toys for children all around the world. Today they need YOUR help splitting materials fairly.",
    next: "meet-bleep",
    sfx: "music-box",
  },
  "meet-bleep": {
    id: "meet-bleep",
    type: "narrate",
    tutorText: "This is Bleep, a friendly robot elf. Bleep has ONE roll of shiny ribbon and needs to share it equally between TWO gift-wrapping stations. Can you help?",
    next: "halves-intro-q",
    sfx: "soft-bell",
  },
  "halves-intro-q": {
    id: "halves-intro-q",
    type: "choice",
    tutorText: "If we cut one roll of ribbon into two EQUAL pieces, what do we call each piece?",
    taskHeader: "What is each piece called?",
    choices: [
      { label: "A third", next: "halves-intro-wrong" },
      { label: "A half", next: "halves-intro-right", correct: true },
      { label: "A quarter", next: "halves-intro-wrong" },
    ],
    sfx: "chime",
  },
  "halves-intro-wrong": {
    id: "halves-intro-wrong",
    type: "narrate",
    tutorText: "Not quite! When we split something into TWO equal pieces, each piece is called a half. Let's try again.",
    next: "halves-intro-q",
    sfx: "gentle-whoosh",
  },
  "halves-intro-right": {
    id: "halves-intro-right",
    type: "narrate",
    tutorText: "That's right! Each piece is called a HALF. Great job!",
    next: "show-half-fraction",
    sfx: "harp-gliss",
  },
  "show-half-fraction": {
    id: "show-half-fraction",
    type: "show-fraction",
    tutorText: "We write one half like this. The bottom number tells us we cut into 2 equal pieces. The top number tells us we have 1 of those pieces.",
    showFractionNum: 1,
    showFractionDen: 2,
    next: "slice-ribbon",
    sfx: "sparkle",
  },
  "slice-ribbon": {
    id: "slice-ribbon",
    type: "slice",
    tutorText: "Now let's slice this ribbon in half! Use the cutter to divide it into 2 equal pieces.",
    cookieCount: 1,
    allowKnife: true,
    next: "distribute-ribbon",
    sfx: "chime",
  },
  "distribute-ribbon": {
    id: "distribute-ribbon",
    type: "distribute-halves",
    tutorText: "Perfect cut! Now give one half to each wrapping station.",
    cookieCount: 2,
    characterCount: 2,
    expectedPerPerson: 1,
    next: "ribbon-done",
    sfx: "soft-bell",
  },
  "ribbon-done": {
    id: "ribbon-done",
    type: "narrate",
    tutorText: "Wonderful! Each station got exactly one half of the ribbon. That's fair sharing! Bleep is so happy.",
    next: "half-check-q",
    sfx: "harp-gliss",
  },
  "half-check-q": {
    id: "half-check-q",
    type: "choice",
    tutorText: "Quick check! How many halves make one whole roll of ribbon?",
    taskHeader: "How many halves in a whole?",
    choices: [
      { label: "1", next: "half-check-wrong" },
      { label: "2", next: "half-check-right", correct: true },
      { label: "3", next: "half-check-wrong" },
    ],
    sfx: "chime",
  },
  "half-check-wrong": {
    id: "half-check-wrong",
    type: "narrate",
    tutorText: "Hmm, not quite. Think about it: we cut one whole into two equal pieces. So it takes 2 halves to make a whole! Try again.",
    next: "half-check-q",
    sfx: "gentle-whoosh",
  },
  "half-check-right": {
    id: "half-check-right",
    type: "narrate",
    tutorText: "Exactly! Two halves make one whole. You really know your fractions!",
    next: "show-two-halves",
    sfx: "harp-gliss",
  },
  "show-two-halves": {
    id: "show-two-halves",
    type: "show-fraction",
    tutorText: "Two halves look like this. See? 2 out of 2 pieces is the whole thing!",
    showFractionNum: 2,
    showFractionDen: 2,
    wholeNumber: 1,
    next: "stage2-intro",
    sfx: "sparkle",
  },

  // ── STAGE 2: Discover 1/2 = 2/4 ────────────────────────────
  "stage2-intro": {
    id: "stage2-intro",
    type: "narrate",
    tutorText: "Great work so far! Now Bleep's friend Whirra rolls in. Whirra has a big sheet of wrapping paper. She wants to try something interesting!",
    next: "whirra-idea",
    sfx: "music-box",
  },
  "whirra-idea": {
    id: "whirra-idea",
    type: "narrate",
    tutorText: "Whirra says: 'What if I cut my wrapping paper into FOUR equal pieces instead of two? I wonder how that compares to cutting it in half...'",
    next: "show-quarter-fraction",
    sfx: "soft-bell",
  },
  "show-quarter-fraction": {
    id: "show-quarter-fraction",
    type: "show-fraction",
    tutorText: "When we cut something into 4 equal pieces, each piece is called one quarter, or one fourth. We write it like this.",
    showFractionNum: 1,
    showFractionDen: 4,
    next: "slice-paper-four",
    sfx: "sparkle",
  },
  "slice-paper-four": {
    id: "slice-paper-four",
    type: "slice",
    tutorText: "Help Whirra cut this wrapping paper into 4 equal pieces!",
    cookieCount: 1,
    allowKnife: true,
    next: "paper-sliced",
    sfx: "chime",
  },
  "paper-sliced": {
    id: "paper-sliced",
    type: "narrate",
    tutorText: "Beautiful! Now we have 4 equal pieces of wrapping paper. Whirra picks up 2 of them.",
    next: "show-two-quarters",
    sfx: "soft-bell",
  },
  "show-two-quarters": {
    id: "show-two-quarters",
    type: "show-fraction",
    tutorText: "Whirra is holding 2 out of 4 pieces. We write that as two quarters, like this!",
    showFractionNum: 2,
    showFractionDen: 4,
    next: "compare-setup",
    sfx: "sparkle",
  },
  "compare-setup": {
    id: "compare-setup",
    type: "narrate",
    tutorText: "Now let's compare! Bleep has one half of a ribbon. Whirra has two quarters of wrapping paper. Both sheets started the same size. Who has MORE paper?",
    next: "compare-q",
    sfx: "warm-pad",
  },
  "compare-q": {
    id: "compare-q",
    type: "choice",
    tutorText: "Bleep has 1/2. Whirra has 2/4. Who has the bigger piece?",
    taskHeader: "Who has more?",
    choices: [
      { label: "Bleep has more", next: "compare-wrong" },
      { label: "They have the same amount!", next: "compare-right", correct: true },
      { label: "Whirra has more", next: "compare-wrong" },
    ],
    sfx: "chime",
  },
  "compare-wrong": {
    id: "compare-wrong",
    type: "narrate",
    tutorText: "Look carefully! If you put Whirra's 2 pieces side by side, they cover exactly the same area as Bleep's 1 piece. They're the same amount! Try again.",
    next: "compare-q",
    sfx: "gentle-whoosh",
  },
  "compare-right": {
    id: "compare-right",
    type: "narrate",
    tutorText: "YES! They have the SAME amount! Even though the numbers look different, one half and two quarters are the SAME size. This is a big discovery!",
    next: "equivalence-reveal",
    sfx: "harp-gliss",
  },
  "equivalence-reveal": {
    id: "equivalence-reveal",
    type: "show-fraction",
    tutorText: "One half EQUALS two quarters! The fractions look different, but they mean the same amount. We call these EQUIVALENT fractions!",
    showFractionNum: 1,
    showFractionDen: 2,
    next: "show-equiv-rhs",
    sfx: "sparkle",
  },
  "show-equiv-rhs": {
    id: "show-equiv-rhs",
    type: "show-fraction",
    tutorText: "See? 1/2 = 2/4. Two quarters is just another way to say one half!",
    showFractionNum: 2,
    showFractionDen: 4,
    next: "why-explain",
    sfx: "sparkle",
  },
  "why-explain": {
    id: "why-explain",
    type: "narrate",
    tutorText: "Here's the secret: if you multiply the top AND the bottom of 1/2 by the same number — like 2 — you get 2/4. The fraction looks different, but the amount stays the same!",
    next: "multiply-check-q",
    sfx: "warm-pad",
  },
  "multiply-check-q": {
    id: "multiply-check-q",
    type: "choice",
    tutorText: "We multiplied the top number 1 by 2 to get 2. What did we multiply the bottom number 2 by?",
    taskHeader: "What did we multiply by?",
    choices: [
      { label: "By 1", next: "multiply-check-wrong" },
      { label: "By 2", next: "multiply-check-right", correct: true },
      { label: "By 4", next: "multiply-check-wrong" },
    ],
    sfx: "chime",
  },
  "multiply-check-wrong": {
    id: "multiply-check-wrong",
    type: "narrate",
    tutorText: "Not quite! We went from 2 on the bottom to 4 on the bottom. What times 2 equals 4? It's 2! We multiplied top and bottom by the same number. Try again.",
    next: "multiply-check-q",
    sfx: "gentle-whoosh",
  },
  "multiply-check-right": {
    id: "multiply-check-right",
    type: "narrate",
    tutorText: "That's it! We multiplied BOTH the top and bottom by 2. Top: 1 times 2 is 2. Bottom: 2 times 2 is 4. So 1/2 = 2/4!",
    next: "celebrate-discovery",
    sfx: "harp-gliss",
  },
  "celebrate-discovery": {
    id: "celebrate-discovery",
    type: "narrate",
    tutorText: "Bleep and Whirra do a happy dance! They discovered that fractions can look different but still be the same amount. That's called equivalence!",
    next: "practice-confirm-q",
    sfx: "music-box",
  },
  "practice-confirm-q": {
    id: "practice-confirm-q",
    type: "choice",
    tutorText: "So if two fractions show the SAME amount, we call them...",
    taskHeader: "What are they called?",
    choices: [
      { label: "Equivalent fractions", next: "practice-confirm-right", correct: true },
      { label: "Bigger fractions", next: "practice-confirm-wrong" },
      { label: "Smaller fractions", next: "practice-confirm-wrong" },
    ],
    sfx: "chime",
  },
  "practice-confirm-wrong": {
    id: "practice-confirm-wrong",
    type: "narrate",
    tutorText: "They're not bigger or smaller — they're the SAME amount! When two fractions mean the same thing, we call them equivalent. Let's try again!",
    next: "practice-confirm-q",
    sfx: "gentle-whoosh",
  },
  "practice-confirm-right": {
    id: "practice-confirm-right",
    type: "narrate",
    tutorText: "You got it! Equivalent fractions. You're becoming a real fraction expert!",
    next: "stage3-intro",
    sfx: "harp-gliss",
  },

  // ── STAGE 3: Practice another equivalence (1/3 = 2/6) ──────
  "stage3-intro": {
    id: "stage3-intro",
    type: "narrate",
    tutorText: "Now a new job comes into the workshop! Three robot elves need to share a long strip of clay for making toy animals. Let's help them!",
    next: "clay-setup",
    sfx: "music-box",
  },
  "clay-setup": {
    id: "clay-setup",
    type: "narrate",
    tutorText: "We have one strip of clay, and we need to cut it into 3 equal pieces — one for each elf.",
    next: "show-one-third",
    sfx: "soft-bell",
  },
  "show-one-third": {
    id: "show-one-third",
    type: "show-fraction",
    tutorText: "Each elf gets one third of the clay. We write one third like this!",
    showFractionNum: 1,
    showFractionDen: 3,
    next: "slice-clay-thirds",
    sfx: "sparkle",
  },
  "slice-clay-thirds": {
    id: "slice-clay-thirds",
    type: "slice",
    tutorText: "Cut the clay into 3 equal pieces for the elves!",
    cookieCount: 1,
    allowKnife: true,
    next: "distribute-clay-thirds",
    sfx: "chime",
  },
  "distribute-clay-thirds": {
    id: "distribute-clay-thirds",
    type: "distribute",
    tutorText: "Now give one piece of clay to each of the 3 robot elves.",
    cookieCount: 3,
    characterCount: 3,
    expectedPerPerson: 1,
    next: "thirds-done",
    sfx: "soft-bell",
  },
  "thirds-done": {
    id: "thirds-done",
    type: "narrate",
    tutorText: "Each elf got one third! But wait — Bleep has an idea. 'What if we had SIX elves instead? Could two of them share the same amount as one elf's third?'",
    next: "sixths-idea",
    sfx: "warm-pad",
  },
  "sixths-idea": {
    id: "sixths-idea",
    type: "narrate",
    tutorText: "Let's test Bleep's idea! Imagine cutting each third in half. Now we'd have 6 equal pieces total. Each old third becomes 2 of the new smaller pieces!",
    next: "show-two-sixths",
    sfx: "soft-bell",
  },
  "show-two-sixths": {
    id: "show-two-sixths",
    type: "show-fraction",
    tutorText: "Two of those six pieces is written like this: two sixths!",
    showFractionNum: 2,
    showFractionDen: 6,
    next: "equiv-thirds-q",
    sfx: "sparkle",
  },
  "equiv-thirds-q": {
    id: "equiv-thirds-q",
    type: "choice",
    tutorText: "If one third of the clay is the same amount as two sixths, are 1/3 and 2/6 equivalent fractions?",
    taskHeader: "Are 1/3 and 2/6 equivalent?",
    choices: [
      { label: "Yes, they are equivalent!", next: "equiv-thirds-right", correct: true },
      { label: "No, they are different.", next: "equiv-thirds-wrong" },
    ],
    sfx: "chime",
  },
  "equiv-thirds-wrong": {
    id: "equiv-thirds-wrong",
    type: "narrate",
    tutorText: "Actually, they ARE the same amount! One third covers exactly the same space as two sixths. They're equivalent! Let's try that again.",
    next: "equiv-thirds-q",
    sfx: "gentle-whoosh",
  },
  "equiv-thirds-right": {
    id: "equiv-thirds-right",
    type: "narrate",
    tutorText: "Yes! 1/3 equals 2/6! Just like 1/2 equals 2/4. You found another pair of equivalent fractions!",
    next: "show-equiv-third",
    sfx: "harp-gliss",
  },
  "show-equiv-third": {
    id: "show-equiv-third",
    type: "show-fraction",
    tutorText: "One third...",
    showFractionNum: 1,
    showFractionDen: 3,
    next: "show-equiv-sixth",
    sfx: "sparkle",
  },
  "show-equiv-sixth": {
    id: "show-equiv-sixth",
    type: "show-fraction",
    tutorText: "...equals two sixths! 1/3 = 2/6. The same amount, just written differently!",
    showFractionNum: 2,
    showFractionDen: 6,
    next: "pattern-q",
    sfx: "sparkle",
  },
  "pattern-q": {
    id: "pattern-q",
    type: "choice",
    tutorText: "Do you see the pattern? To go from 1/3 to 2/6, we multiplied the top and bottom by...",
    taskHeader: "We multiplied by what?",
    choices: [
      { label: "2", next: "pattern-right", correct: true },
      { label: "3", next: "pattern-wrong" },
      { label: "6", next: "pattern-wrong" },
    ],
    sfx: "chime",
  },
  "pattern-wrong": {
    id: "pattern-wrong",
    type: "narrate",
    tutorText: "Let's check: 1 times what equals 2? And 3 times what equals 6? The answer is 2 for both! We multiplied top and bottom by 2. Try again!",
    next: "pattern-q",
    sfx: "gentle-whoosh",
  },
  "pattern-right": {
    id: "pattern-right",
    type: "narrate",
    tutorText: "Fantastic! Multiply top and bottom by 2. 1 times 2 is 2, and 3 times 2 is 6. So 1/3 = 2/6. You've mastered the pattern!",
    next: "bonus-challenge-intro",
    sfx: "harp-gliss",
  },
  "bonus-challenge-intro": {
    id: "bonus-challenge-intro",
    type: "narrate",
    tutorText: "Bleep and Whirra have one last challenge for you! The workshop is making a big batch of toy paint, and they need to figure out one more equivalent fraction.",
    next: "bonus-q",
    sfx: "music-box",
  },
  "bonus-q": {
    id: "bonus-q",
    type: "choice",
    tutorText: "If 1/2 = 2/4, and 1/3 = 2/6, then what do you think 1/4 equals? Multiply the top and bottom by 2!",
    taskHeader: "1/4 = ?",
    choices: [
      { label: "2/6", next: "bonus-wrong" },
      { label: "2/8", next: "bonus-right", correct: true },
      { label: "3/8", next: "bonus-wrong" },
    ],
    sfx: "chime",
  },
  "bonus-wrong": {
    id: "bonus-wrong",
    type: "narrate",
    tutorText: "Almost! Remember the trick: multiply BOTH the top and bottom by 2. The top: 1 times 2 = 2. The bottom: 4 times 2 = 8. Try once more!",
    next: "bonus-q",
    sfx: "gentle-whoosh",
  },
  "bonus-right": {
    id: "bonus-right",
    type: "narrate",
    tutorText: "YES! 1/4 = 2/8! You multiplied top and bottom by 2 perfectly. 1 times 2 is 2, and 4 times 2 is 8!",
    next: "show-bonus-fraction",
    sfx: "harp-gliss",
  },
  "show-bonus-fraction": {
    id: "show-bonus-fraction",
    type: "show-fraction",
    tutorText: "One quarter equals two eighths! Another equivalent fraction, solved by YOU!",
    showFractionNum: 2,
    showFractionDen: 8,
    next: "wrap-up",
    sfx: "sparkle",
  },
  "wrap-up": {
    id: "wrap-up",
    type: "narrate",
    tutorText: "All the robot elves in the Toy Workshop are cheering for you! You learned that fractions can look different but still mean the same amount.",
    next: "recap1",
    sfx: "xylophone",
  },
  "recap1": {
    id: "recap1",
    type: "show-fraction",
    tutorText: "You learned that one half...",
    showFractionNum: 1,
    showFractionDen: 2,
    next: "recap2",
    sfx: "soft-bell",
  },
  "recap2": {
    id: "recap2",
    type: "show-fraction",
    tutorText: "...is the same as two quarters! Equivalent fractions!",
    showFractionNum: 2,
    showFractionDen: 4,
    next: "recap3",
    sfx: "sparkle",
  },
  "recap3": {
    id: "recap3",
    type: "narrate",
    tutorText: "And you discovered the secret: multiply the top AND the bottom by the same number, and you get an equivalent fraction. The amount never changes!",
    next: "final-goodbye",
    sfx: "warm-pad",
  },
  "final-goodbye": {
    id: "final-goodbye",
    type: "narrate",
    tutorText: "Bleep and Whirra wave goodbye. 'Come back soon!' they say. 'There are always more toys to build and more fractions to discover!' Great work today, fraction champion!",
    next: "end",
    sfx: "music-box",
  },
};
